source 'https://rubygems.org'

gem 'rails'
gem 'rails-i18n'
gem 'mongoid', '~> 3.0.0'
gem 'mongoid_slug'
gem 'slim-rails'
gem 'jquery-rails'
gem 'backbone-on-rails'
gem 'jbuilder'
gem 'kaminari'
gem 'simple_form'
gem 'rails_autolink'
gem 'client_side_validations'
gem 'carrierwave'
gem 'devise'
gem 'capistrano'
gem 'rvm-capistrano'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'compass-rails'
  gem 'bootstrap-sass'
  gem 'handlebars_assets'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'mongoid-rspec'
  gem 'fabrication'
  gem 'ffaker'
  gem 'jasminerice'
  gem 'guard-spork'
  gem 'guard-rspec'
  gem 'guard-jasmine'
  gem 'guard-livereload'
  gem 'database_cleaner'
  gem 'rb-fsevent'
  gem 'growl'
  gem 'rb-inotify'
  gem 'libnotify'
end
