source 'https://rubygems.org'

gem 'rails'
gem 'rails-i18n'
gem 'mongoid', '~> 3.0.0'
gem 'mongoid_slug'
gem 'slim-rails'
gem 'jquery-rails'
gem 'backbone-on-rails'
gem 'jbuilder'
gem 'kaminari'
gem 'simple_form'
gem 'rails_autolink'
gem 'client_side_validations'
gem 'bootstrap-wysihtml5-rails'
gem 'carrierwave'
gem 'carrierwave-mongoid'
gem 'carrierwave-upyun'
gem 'devise'
gem 'omniauth-weibo-oauth2'
gem 'weibo_2'
gem 'cancan'
gem 'settingslogic'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'airbrake'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'compass-rails'
  gem 'bootstrap-sass'
  gem 'font-awesome-sass-rails'
  gem 'handlebars_assets'
  gem "jquery-fileupload-rails"
  gem 'turbo-sprockets-rails3'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'mongoid-rspec'
  gem 'fabrication'
  gem 'ffaker'
  gem 'jasminerice'
  gem 'guard-spork'
  gem 'guard-rspec'
  gem 'guard-jasmine'
  gem 'guard-livereload'
  gem 'database_cleaner'
  gem 'rb-fsevent'
  gem 'growl'
  gem 'thin'
  gem 'quiet_assets'
end
